### PR TITLE
Handle Ext.require and override and fix some bugs

### PR DESCRIPTION
**Pull request by dedesite**
Hi,

I've been working since last week on grunt-extjs-dependencies in order to get rid of sencha cmd.
I found it quit good but lacked some functionalities like Ext.require and a proper way to handle override.
I also fixed a couple of very annoying bug and add some test data.
Hope you'll appreciate my modifications and merge them :).

There is still one bug to fix. It's about namespaces, the files that create them must be in first position even if it isn't first in the required order but I found a workaround by adding those files manually in the concat task.
And, the skip parameter isn't working properly but it's ok.

Thanks for this plugin,
Andréas

### CODE REVIEW

**Comment by cpak** [comment]
Hi Andréas,
sorry I took so long getting back to you. I don't seem to get notifications from this repo.

Anyways, your changes seem legit and I'd be glad to merge. However the tests fail when I check out your branch. Is that to be expected?

**Comment by dedesite** [comment]
Sorry, I worked with my own tests and didn't looked at yours... I'll update them quickly and update the pull request soon.

**Comment by dedesite** [comment]
Done. I think it's ok now. I remove the vendor file cause it's not parsed as stated in the Gruntfile. Tell me if there is something wrong.

**Comment by cpak** [comment]
Thanks for contributing, glad you've found use for this plugin :)

**Comment by dedesite** [comment]
Thanks for creating it first :). We try to get rid of sencha cmd and use grunt tasks only so listing application dependencies is the first step. Hope we'll be able to replace the entire workflow !

**Pull request merged**
